USE [CAP_INTER]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [LDS_CLE_2]    Script Date: 8/28/2024 9:15:38 AM ******/
CREATE NONCLUSTERED INDEX [LDS_CLE_2] ON [dbo].[T_PIECE]
(
	[GP_ETABLISSEMENT] ASC,
	[GP_NUMERO] ASC,
	[GP_NATUREPIECE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


