USE [CAP_INTER]
GO

/****** Object:  Index [LDS_CLE_3]    Script Date: 8/28/2024 9:17:40 AM ******/
CREATE NONCLUSTERED INDEX [LDS_CLE_3] ON [dbo].[T_LIGNE]
(
	[GL_NUMERO] ASC,
	[GL_DATEPIECE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


